[project]
# Use /tmp for writable storage on Hugging Face Spaces
user_env = []
cache = false

[features]
multi_modal = false
unsafe_allow_html = false
latex = false

[UI]
name = "RAG Chatbot"
show_readme_as_default = true

[meta]
generated_by = "0.7.0"